UI-MVC/Models/ErrorViewModel.cs
namespace Spaceflight.UI.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UI-MVC/Models/NewAstronautViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Spaceflight.BL.Domain;

namespace Spaceflight.UI.MVC.Models
{
    public class NewAstronautViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public DateTime BirthYear { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public int Id { get; set; }
    }
}

UI-MVC/Controllers/AstronautController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Spaceflight.BL;
using Spaceflight.BL.Domain;
using Spaceflight.UI.MVC.Models;

namespace Spaceflight.UI.MVC.Controllers
{
    public class AstronautController : Controller
    {
        private IManager _manager;

        public AstronautController()
        {
            _manager = new Manager();
        }
        
        public IActionResult Index()
        {
            return View(_manager.GetAllAstronautsWithAgency());
        }
        
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Agency = _manager.GetAllAgencies();
            return View();
        }
        
        [HttpPost]
        public IActionResult Add([FromForm] NewAstronautViewModel astronautViewModel)
        {
            ViewBag.Agency = _manager.GetAllAgencies();
            if (!ModelState.IsValid)
            {
                return View();
            }
            Astronaut a;
            Agency agency = _manager.GetAgency(astronautViewModel.Id);
            a = _manager.AddAstronaut(astronautViewModel.Name, astronautViewModel.BirthYear, astronautViewModel.Gender, agency);
            return RedirectToAction("Detail", new {id = a.Id});
        }
        
        public IActionResult Detail(int id)
        {
            ViewBag.Astronaut = _manager.GetAstronaut(id);
            ViewBag.Mission = _manager.GetAstronautWithMissions(id);
            ViewBag.UnassignedMission = _manager.GetAstronautWithoutMissions(id);
            return View();
        }

        public IActionResult LinkMission(int astronautId, int missionId)
        { 
            Astronaut chosenAstronaut = _manager.GetAstronaut(astronautId);
            Mission chosenMission = _manager.GetMission(missionId);
            AstronautMission astronautMission = new AstronautMission()
            {
                Astronaut = chosenAstronaut,
                Mission = chosenMission
            };
            _manager.AddAstronautMission(astronautMission);
            return RedirectToAction("Detail", new {id = astronautId});
        }
        
        public IActionResult DeleteMission(int astronautId, int missionId)
        { 
            _manager.RemoveAstronautMission(astronautId, missionId);
            return RedirectToAction("Detail", new {id = astronautId});
        }

        [HttpGet]
        public IActionResult FilterOnNameAndDOB(string name, string dob)
        {
            IEnumerable<Astronaut> astronauts = _manager.GetAstronautsByNameAndDob(name, dob);
            return View(astronauts);
        }
        
    }
}

UI-MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Spaceflight.UI.MVC.Models;

namespace Spaceflight.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UI-MVC/Controllers/MissionController.cs
using Microsoft.AspNetCore.Mvc;
using Spaceflight.BL;

namespace Spaceflight.UI.MVC.Controllers
{
    public class MissionController : Controller
    {
        private IManager _manager;

        public MissionController()
        {
            _manager = new Manager();
        }

        
        public IActionResult Details(int id)
        {
            return View(_manager.GetMission(id));
        }
    }
}

UI-MVC/Views/Astronaut/Add.cshtml
@using Spaceflight.BL
@using Spaceflight.BL.Domain
@model Spaceflight.UI.MVC.Models.NewAstronautViewModel



@{
    ViewBag.Title = "Add Astronaut";
    IEnumerable<Agency> agencies = ViewBag.Agency as IEnumerable<Agency>;
    Layout = "_Layout";
}

<h2>Add Astronaut</h2>

<form asp-controller="Astronaut" asp-action="Add" method="post">
    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
    
    <div class="form-group">
        <label asp-for="Name">Name: </label>
        <input asp-for="Name" type="text" name="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="Name">Gender: </label>
        <select asp-for="Gender" class="form-control">
            <option value="Male">Male</option>
            <option value="Female">Female</option>
        </select>
    </div>
    
    <div class="form-group">
        <label asp-for="BirthYear">Birthdate:</label>
        <input asp-for="BirthYear" class="form-control">
        <span asp-validation-for="BirthYear" class="text-danger"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="Id">Agency: </label>
        <select asp-for="Id" class="form-control">
            @foreach (var a in agencies)
            {
                <option value="@a.Id">@a.Name</option>
            }
        </select>
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    
    <button type="submit">Save</button>
</form>

UI-MVC/Views/Astronaut/Detail.cshtml
@using Spaceflight.BL.Domain
@model Spaceflight.BL.Domain.Astronaut

@{
    ViewBag.Title = "Astronaut Details";
    Layout = "_Layout";
    Astronaut astronaut = ViewBag.Astronaut as Astronaut;
    IEnumerable<Mission> mission = ViewBag.Mission as IEnumerable<Mission>;
    IEnumerable<Mission> unassignedMission = ViewBag.UnassignedMission as IEnumerable<Mission>;
}

<h2 class="font-weight-bolder" >Astronaut</h2>
<dl>
    <dt>Full Name:</dt>
    <dd>@astronaut.Name</dd>
    <dt>Birthdate</dt>
    <dd>@astronaut.BirthYear.ToString("yyyy/MM/dd")</dd>
    <dt>Gender</dt>
    <dd>@astronaut.Gender</dd>

    <h3 class="font-weight-bolder">Assigned Missions:</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th></th>
            <th></th>
        </tr>
        </thead>

        @foreach (var m in mission)
        {
            <tr>
                <td>@m.MissionName</td>
                <td>@m.MissionType</td>
                <td><a class="nav-link text-dark" asp-controller="Mission" asp-action="Details" asp-route-id="@m.Id">Detail</a></td>
                <td><a class="nav-link text-dark" asp-controller="Astronaut" asp-action="DeleteMission" asp-route-astronautId="@astronaut.Id" asp-route-missionId="@m.Id">Delete</a></td>
            </tr>
        }
    </table>
    
    <h3 class="font-weight-bolder">Available Missions:</h3>
        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
    
            @foreach (var m in unassignedMission)
            {
                <tr>
                    <td>@m.MissionName</td>
                    <td>@m.MissionType</td>
                    <td><a class="nav-link text-dark" asp-controller="Mission" asp-action="Details" asp-route-id="@m.Id">Detail</a></td>
                    <td><a class="nav-link text-dark" asp-controller="Astronaut" asp-action="LinkMission" asp-route-astronautId="@astronaut.Id" asp-route-missionId="@m.Id">Add</a></td>
                </tr>
            }
        </table>
    
</dl>

UI-MVC/Views/Astronaut/FilterOnNameAndDOB.cshtml
@model System.Collections.Generic.IEnumerable<Spaceflight.BL.Domain.Astronaut>

@{
    ViewBag.Title = "Astronauts Filtered";
    Layout = "_Layout";
}

<h2>Astronauts Found:</h2>
<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Date of Birth</th>
        <th>Gender</th>
        <th></th>
    </tr>
    </thead>

    @foreach (var astronaut in Model)
    {
        <tr>
            <td>@astronaut.Id</td>
            <td>@astronaut.Name</td>
            <td>@astronaut.BirthYear.ToString("yyyy/MM/dd")</td>
            <td>@astronaut.Gender</td>

            <td><a class="nav-link text-dark" asp-controller="Astronaut" asp-action="Detail" asp-route-id="@astronaut.Id">Detail</a></td>
        </tr>
    }
</table>

UI-MVC/Views/Astronaut/Index.cshtml
@model IEnumerable<Spaceflight.BL.Domain.Astronaut>

@{
    ViewBag.Title = "All Astronauts";
    Layout = "_Layout";
}

<h2>All Astronauts</h2>
<div class="col-md-4 form-inline">
    <form asp-controller="Astronaut" asp-action="FilterOnNameAndDOB" method="get" class="form-group">
        <p>Filter Astronauts based on Name and/or DOB:  </p>
        <input name="Name" placeholder="John" class="form-control"/>
        <input name="Dob" placeholder="12/10/2001" class="form-control"/>
        <input type="submit" value="Show Astronaut" class="btn btn-light"/>
    </form>
</div>
<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Date of Birth</th>
        <th>Gender</th>
        <th>Agency</th>
        <th></th>
    </tr>
    </thead>

    @foreach (var astronaut in Model)
    {
        <tr>
            <td>@astronaut.Id</td>
            <td>@astronaut.Name</td>
            <td>@astronaut.BirthYear.ToString("yyyy/MM/dd")</td>
            <td>@astronaut.Gender</td>
            <td>@astronaut.Agency.Name</td>
            <td><a class="nav-link text-dark" asp-controller="Astronaut" asp-action="Detail" asp-route-id="@astronaut.Id">Detail</a></td>
        </tr>
    }
</table>

UI-MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UI-MVC/Views/Mission/Details.cshtml
@model Spaceflight.BL.Domain.Mission

@{
    ViewBag.Title = "Mission Details";
    Layout = "_Layout";
}

<h2 class="font-weight-bolder" >Mission</h2>
<dl>
    <dt>Mission Name:</dt>
    <dd>@Model.MissionName</dd>
    <dt>Mission Type:</dt>
    <dd>@Model.MissionType</dd>
</dl>

UI-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Astronaut Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Astronaut" asp-action="Index">Astronaut Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Astronaut" asp-action="Add">Add Astronaut</a>
                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - KdG - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>